const BASE_TEN = 10;
const BIT_OFF = 0;
const BIT_ON = 1;
const DEFAULT_PROBLEM_DOMAIN = 'ONE_MAX';
const DEFAULT_SCHEMA = [1, 1];
const DEFAULT_SCHEMA_DEFINING_ORDER = 2;
const DEFAULT_SCHEMA_SCHEMA_ORDER = 3;
const DEGREES_MAX = 359;
const DEGREES_MIN = 0;

module.exports = {
  BASE_TEN: BASE_TEN,
  BIT_OFF: BIT_OFF,
  BIT_ON: BIT_ON,
  DEFAULT_PROBLEM_DOMAIN: DEFAULT_PROBLEM_DOMAIN,
  DEFAULT_SCHEMA: DEFAULT_SCHEMA,
  DEFAULT_SCHEMA_DEFINING_ORDER: DEFAULT_SCHEMA_DEFINING_ORDER,
  DEGREES_MAX: DEGREES_MAX,
  DEGREES_MIN: DEGREES_MIN,
};
